[project]
name = 'starter-contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.bitcoin-crowdfunding]
path = 'contracts/bitcoin-crowdfunding.clar'
clarity_version = 3
epoch = 3.0

[contracts.campaign-management]
path = 'contracts/campaign-management.clar'
clarity_version = 3
epoch = 3.0

[contracts.project-verification]
path = 'contracts/project-verification.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
